apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
        - name: worker
          image: ai-devops-copilot_worker:latest
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: worker-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: worker-config
data:
  RABBITMQ_URL: "amqp://rabbitmq:5672"
  QUEUE_NAME: "tasks.queue"